discord:
  token: ${DISCORD_BOT_TOKEN}

server:
  port: ${BOT_SERVICE_PORT}

backend:
  url: ${BACKEND_URL}

security:
  internal-token: ${INTERNAL_SECURITY_TOKEN}
  internal-token-header: X-Internal-Token

logging:
  pattern:
    console: "[%d{HH:mm:ss-dd/MM/yyyy}] - [%logger{0}] %msg%n"